// <auto-generated />
using System;
using System.Net;
using Authorization.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Authorization.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuthorizationDbContext))]
    partial class AuthorizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("authz")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.AiInvocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActorEmail")
                        .HasColumnType("text")
                        .HasColumnName("actor_email");

                    b.Property<string>("ActorRole")
                        .HasColumnType("text")
                        .HasColumnName("actor_role");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.HasIndex("Feature", "Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("ai_invocations", "authz");
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.AiPromptLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActorEmail")
                        .HasColumnType("text")
                        .HasColumnName("actor_email");

                    b.Property<string>("ActorRole")
                        .HasColumnType("text")
                        .HasColumnName("actor_role");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature");

                    b.Property<string>("Interpretation")
                        .HasColumnType("jsonb")
                        .HasColumnName("interpretation");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.HasIndex("Feature", "Timestamp")
                        .IsDescending(false, true);

                    b.HasIndex("Outcome", "Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("ai_prompt_logs", "authz");
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.ApplicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<string>("BusinessOwner")
                        .HasColumnType("text")
                        .HasColumnName("business_owner");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OwnerTeam")
                        .HasColumnType("text")
                        .HasColumnName("owner_team");

                    b.Property<string>("PolicyCombiningAlgorithm")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("deny-overrides")
                        .HasColumnName("policy_combining_algorithm");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("MEDIUM")
                        .HasColumnName("risk_level");

                    b.Property<string>("SourceOfTruthMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PLATFORM_OWNED")
                        .HasColumnName("source_of_truth_mode");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<string>("TechnicalOwner")
                        .HasColumnType("text")
                        .HasColumnName("technical_owner");

                    b.Property<Guid>("TenantRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_ref_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("ApplicationId");

                    b.HasIndex("TenantRefId");

                    b.ToTable("applications", "authz", t =>
                        {
                            t.HasCheckConstraint("ck_applications_policy_combining_algorithm", "policy_combining_algorithm in ('deny-overrides', 'allow-overrides', 'first-applicable')");

                            t.HasCheckConstraint("ck_applications_risk_level", "risk_level in ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')");

                            t.HasCheckConstraint("ck_applications_source_of_truth_mode", "source_of_truth_mode in ('PLATFORM_OWNED', 'EXTERNAL_READ', 'DUAL_WRITE', 'EXTERNAL_OWNED')");

                            t.HasCheckConstraint("ck_applications_status", "status in ('ACTIVE', 'DISABLED', 'DEPRECATED', 'ARCHIVED')");
                        });
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.AssignmentAttributeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value_type");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId", "Name")
                        .IsUnique();

                    b.ToTable("assignment_attributes", "authz", t =>
                        {
                            t.HasCheckConstraint("ck_assignment_attributes_value_type", "value_type in ('string', 'number', 'boolean', 'string[]', 'number[]')");
                        });
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.AssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_ref_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("GroupId")
                        .HasColumnType("text")
                        .HasColumnName("group_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ResourceId")
                        .HasColumnType("text")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("RoleRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_ref_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("MANUAL")
                        .HasColumnName("source");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("state");

                    b.Property<string>("SubjectEmail")
                        .HasColumnType("text")
                        .HasColumnName("subject_email");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("RoleRefId");

                    b.HasIndex("ApplicationRefId", "RoleRefId", "State");

                    b.HasIndex("ApplicationRefId", "SubjectEmail", "State", "ValidFrom", "ValidUntil");

                    b.ToTable("assignments", "authz", t =>
                        {
                            t.HasCheckConstraint("ck_assignments_source", "source in ('MANUAL', 'IMPORT', 'WORKFLOW', 'LIFECYCLE', 'EMERGENCY')");

                            t.HasCheckConstraint("ck_assignments_state", "state in ('ACTIVE', 'EXPIRED', 'REVOKED')");

                            t.HasCheckConstraint("ck_assignments_subject_type", "subject_type in ('USER', 'GROUP', 'SERVICE_ACCOUNT', 'EXTERNAL_USER', 'TENANT', 'APPLICATION')");
                        });
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.AuditEventEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActorClientId")
                        .HasColumnType("text")
                        .HasColumnName("actor_client_id");

                    b.Property<string>("ActorEmail")
                        .HasColumnType("text")
                        .HasColumnName("actor_email");

                    b.Property<string>("ActorRole")
                        .HasColumnType("text")
                        .HasColumnName("actor_role");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<IPAddress>("SourceIp")
                        .HasColumnType("inet")
                        .HasColumnName("source_ip");

                    b.Property<string>("TargetSubjectEmail")
                        .HasColumnType("text")
                        .HasColumnName("target_subject_email");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.HasKey("EventId");

                    b.HasIndex("ActorEmail", "Timestamp")
                        .IsDescending(false, true);

                    b.HasIndex("ApplicationId", "Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("audit_events", "authz");
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.DecisionEntity", b =>
                {
                    b.Property<string>("DecisionId")
                        .HasColumnType("text")
                        .HasColumnName("decision_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<bool>("Allowed")
                        .HasColumnType("boolean")
                        .HasColumnName("allowed");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<string>("ContextSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("context_snapshot");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DenyReason")
                        .HasColumnType("text")
                        .HasColumnName("deny_reason");

                    b.PrimitiveCollection<string[]>("MatchedPermissions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("matched_permissions")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.PrimitiveCollection<string[]>("MatchedPolicies")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("matched_policies")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.PrimitiveCollection<string[]>("MatchedRoles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("matched_roles")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<string>("Obligations")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("obligations")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("ResourceId")
                        .HasColumnType("text")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.Property<string>("SubjectEmail")
                        .HasColumnType("text")
                        .HasColumnName("subject_email");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VersionsUsed")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("versions_used")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("DecisionId");

                    b.HasIndex("DecisionId")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "Timestamp")
                        .IsDescending(false, true);

                    b.HasIndex("SubjectEmail", "Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("decisions", "authz");
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.OidcProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.PrimitiveCollection<string[]>("AllowedAlgorithms")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_algorithms")
                        .HasDefaultValueSql("ARRAY['RS256']::text[]");

                    b.Property<Guid>("ApplicationRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_ref_id");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audience");

                    b.Property<string>("ClaimMappings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("claim_mappings")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer");

                    b.Property<string>("JwksUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jwks_uri");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("OIDC")
                        .HasColumnName("provider_type");

                    b.Property<string>("RequiredClaims")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("required_claims")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.PrimitiveCollection<string[]>("RequiredScopes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("required_scopes")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<string>("SubjectClaim")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("sub")
                        .HasColumnName("subject_claim");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("USER")
                        .HasColumnName("subject_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.Property<Guid>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("version_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationRefId");

                    b.ToTable("oidc_providers", "authz", t =>
                        {
                            t.HasCheckConstraint("ck_oidc_providers_no_alg_none", "not ('none' = any(allowed_algorithms))");

                            t.HasCheckConstraint("ck_oidc_providers_provider_type", "provider_type in ('OIDC')");
                        });
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.PermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid>("ApplicationRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_ref_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permission_key");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("MEDIUM")
                        .HasColumnName("risk_level");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("ApplicationRefId", "PermissionKey");

                    b.HasIndex("ApplicationRefId");

                    b.ToTable("permissions", "authz", t =>
                        {
                            t.HasCheckConstraint("ck_permissions_risk_level", "risk_level in ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')");

                            t.HasCheckConstraint("ck_permissions_status", "status in ('ACTIVE', 'DISABLED', 'DEPRECATED', 'ARCHIVED')");
                        });
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.PolicyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_ref_id");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effect");

                    b.Property<string>("Obligations")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("obligations")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Guid>("PermissionRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_ref_id");

                    b.Property<string>("PolicyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_key");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.Property<Guid>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("version_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("Id");

                    b.HasIndex("PermissionRefId");

                    b.HasIndex("ApplicationRefId", "PolicyKey", "VersionId")
                        .IsUnique();

                    b.HasIndex("ApplicationRefId", "PermissionRefId", "State", "PublishedAt");

                    b.ToTable("policies", "authz", t =>
                        {
                            t.HasCheckConstraint("ck_policies_effect", "effect in ('ALLOW', 'DENY')");

                            t.HasCheckConstraint("ck_policies_state", "state in ('DRAFT', 'REVIEW', 'APPROVED', 'PUBLISHED')");
                        });
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.ReferenceDataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_ref_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("ApplicationRefId", "Key");

                    b.HasIndex("ApplicationRefId", "Status");

                    b.ToTable("reference_data", "authz", t =>
                        {
                            t.HasCheckConstraint("ck_reference_data_status", "status in ('ACTIVE', 'ARCHIVED')");
                        });
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.ReviewCampaignEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_ref_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationRefId");

                    b.ToTable("review_campaigns", "authz", t =>
                        {
                            t.HasCheckConstraint("ck_review_campaigns_status", "status in ('DRAFT', 'ACTIVE', 'CLOSED')");
                        });
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.ReviewItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AssignmentRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_ref_id");

                    b.Property<Guid>("CampaignRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_ref_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .HasColumnType("text")
                        .HasColumnName("decided_by");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("decision");

                    b.Property<string>("DecisionNote")
                        .HasColumnType("text")
                        .HasColumnName("decision_note");

                    b.Property<string>("RoleKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_key");

                    b.Property<string>("SubjectEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_email");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CampaignRefId");

                    b.ToTable("review_items", "authz", t =>
                        {
                            t.HasCheckConstraint("ck_review_items_decision", "decision in ('PENDING', 'KEEP', 'REVOKE', 'NEEDS_INFO')");
                        });
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_ref_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Privileged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("privileged");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("MEDIUM")
                        .HasColumnName("risk_level");

                    b.Property<string>("RoleKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("ApplicationRefId", "RoleKey");

                    b.HasIndex("ApplicationRefId");

                    b.ToTable("roles", "authz", t =>
                        {
                            t.HasCheckConstraint("ck_roles_risk_level", "risk_level in ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')");

                            t.HasCheckConstraint("ck_roles_status", "status in ('ACTIVE', 'DISABLED', 'DEPRECATED', 'ARCHIVED')");
                        });
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.RolePermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_ref_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("PermissionRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_ref_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("RoleRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_ref_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.Property<Guid>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("version_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("Id");

                    b.HasIndex("PermissionRefId");

                    b.HasIndex("RoleRefId");

                    b.HasIndex("ApplicationRefId", "PermissionRefId", "State");

                    b.HasIndex("ApplicationRefId", "RoleRefId", "State", "PublishedAt");

                    b.ToTable("role_permissions", "authz", t =>
                        {
                            t.HasCheckConstraint("ck_role_permissions_state", "state in ('DRAFT', 'REVIEW', 'APPROVED', 'PUBLISHED')");
                        });
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.SodRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_ref_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("MatcherA")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("matcher_a");

                    b.Property<string>("MatcherB")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("matcher_b");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Rationale")
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_key");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("HIGH")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("ApplicationRefId", "RuleKey");

                    b.HasIndex("ApplicationRefId");

                    b.ToTable("sod_rules", "authz", t =>
                        {
                            t.HasCheckConstraint("ck_sod_rules_severity", "severity in ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')");

                            t.HasCheckConstraint("ck_sod_rules_status", "status in ('ACTIVE', 'DISABLED', 'ARCHIVED')");
                        });
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.TenantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId");

                    b.ToTable("tenants", "authz", t =>
                        {
                            t.HasCheckConstraint("ck_tenants_status", "status in ('ACTIVE', 'DISABLED', 'ARCHIVED')");
                        });
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.ApplicationEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Persistence.TenantEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.AssignmentAttributeEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Persistence.AssignmentEntity", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.AssignmentEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Persistence.ApplicationEntity", null)
                        .WithMany()
                        .HasForeignKey("ApplicationRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Authorization.Infrastructure.Persistence.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.OidcProviderEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Persistence.ApplicationEntity", null)
                        .WithMany()
                        .HasForeignKey("ApplicationRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.PermissionEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Persistence.ApplicationEntity", null)
                        .WithMany()
                        .HasForeignKey("ApplicationRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.PolicyEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Persistence.ApplicationEntity", null)
                        .WithMany()
                        .HasForeignKey("ApplicationRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Authorization.Infrastructure.Persistence.PermissionEntity", null)
                        .WithMany()
                        .HasForeignKey("PermissionRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.ReferenceDataEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Persistence.ApplicationEntity", null)
                        .WithMany()
                        .HasForeignKey("ApplicationRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.ReviewCampaignEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Persistence.ApplicationEntity", null)
                        .WithMany()
                        .HasForeignKey("ApplicationRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.ReviewItemEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Persistence.ReviewCampaignEntity", null)
                        .WithMany()
                        .HasForeignKey("CampaignRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.RoleEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Persistence.ApplicationEntity", null)
                        .WithMany()
                        .HasForeignKey("ApplicationRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.RolePermissionEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Persistence.ApplicationEntity", null)
                        .WithMany()
                        .HasForeignKey("ApplicationRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Authorization.Infrastructure.Persistence.PermissionEntity", null)
                        .WithMany()
                        .HasForeignKey("PermissionRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Authorization.Infrastructure.Persistence.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Authorization.Infrastructure.Persistence.SodRuleEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Persistence.ApplicationEntity", null)
                        .WithMany()
                        .HasForeignKey("ApplicationRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
