using System.Text;
using System.Text.Json;

namespace Authorization.Ai;

/// <summary>
/// Deterministic, offline stub of <see cref="IAiAssistant"/>. Produces valid,
/// predictable output without contacting any external provider. Used for tests and
/// for local development when no model is configured (<c>Ai:Provider = "Fake"</c>).
/// </summary>
public sealed class FakeAiAssistant : IAiAssistant
{
    private const string StubWarning = "Generated by the local stub assistant. No live model is configured, so this is a deterministic placeholder — review carefully before accepting.";

    public Task<PolicyDraftResult> DraftPolicyAsync(PolicyDraftRequest request, CancellationToken cancellationToken)
    {
        // Build a minimal but valid "all" condition group. When the caller advertises
        // known attributes we seed a single illustrative leaf so the draft is non-empty.
        var conditions = new List<object>();
        string? attribute = request.KnownAttributes.Count > 0 ? request.KnownAttributes[0] : null;
        if (attribute is not null)
        {
            conditions.Add(new
            {
                attribute,
                @operator = "exists",
                value = (string?)null,
            });
        }

        var group = new
        {
            match = "all",
            conditions,
        };

        string json = JsonSerializer.Serialize(group);

        var summary = new StringBuilder()
            .Append("Stub draft for instruction: ")
            .Append(Truncate(request.Instruction, 200))
            .ToString();

        var result = new PolicyDraftResult(
            ConditionsJson: json,
            Summary: summary,
            Warnings: [StubWarning],
            SuggestedEffect: PolicyEffectInference.FromInstruction(request.Instruction));

        return Task.FromResult(result);
    }

    public Task<DecisionExplanationResult> ExplainDecisionAsync(DecisionExplanationRequest request, CancellationToken cancellationToken)
    {
        var narrative = new StringBuilder();
        narrative
            .Append("The request to ")
            .Append(request.Action)
            .Append(" on ")
            .Append(request.ResourceType);
        if (!string.IsNullOrWhiteSpace(request.ResourceId))
        {
            narrative.Append(" '").Append(request.ResourceId).Append('\'');
        }

        narrative.Append(request.Allowed ? " was ALLOWED" : " was DENIED");

        if (request.MatchedRoles.Count > 0)
        {
            narrative.Append(". Matched roles: ").Append(string.Join(", ", request.MatchedRoles));
        }

        if (request.MatchedPermissions.Count > 0)
        {
            narrative.Append(". Matched permissions: ").Append(string.Join(", ", request.MatchedPermissions));
        }

        if (!request.Allowed && !string.IsNullOrWhiteSpace(request.DenyReason))
        {
            narrative.Append(". Deny reason: ").Append(request.DenyReason);
        }

        narrative.Append('.');

        if (request.Allowed)
        {
            return Task.FromResult(new DecisionExplanationResult(narrative.ToString(), []));
        }

        AppendDiagnosticNarrative(narrative, request.Diagnostics);
        IReadOnlyList<string> remediation = BuildRemediation(request);

        return Task.FromResult(new DecisionExplanationResult(narrative.ToString(), remediation));
    }

    public Task<ImpactNarrationResult> NarrateImpactAsync(ImpactNarrationRequest request, CancellationToken cancellationToken)
    {
        var summary = new StringBuilder();
        summary.Append("Publishing ").Append(request.PolicyKey)
            .Append(" (").Append(request.Effect).Append(") ");

        if (request.EvaluatedCount == 0)
        {
            summary.Append("has no representative traffic to evaluate yet, so its impact cannot be measured. ")
                .Append("Simulate a few requests for this resource and action first.");
            return Task.FromResult(new ImpactNarrationResult(summary.ToString()));
        }

        int total = request.AllowToDenyCount + request.DenyToAllowCount;
        if (total == 0)
        {
            summary.Append("changes no outcomes across ").Append(request.EvaluatedCount)
                .Append(request.EvaluatedCount == 1 ? " evaluated request." : " evaluated requests.");
        }
        else
        {
            summary.Append("changes ").Append(total)
                .Append(total == 1 ? " outcome" : " outcomes")
                .Append(" across ").Append(request.EvaluatedCount)
                .Append(request.EvaluatedCount == 1 ? " evaluated request" : " evaluated requests")
                .Append(": ");
            var parts = new List<string>();
            if (request.AllowToDenyCount > 0)
            {
                parts.Add($"{request.AllowToDenyCount} will newly be denied");
            }

            if (request.DenyToAllowCount > 0)
            {
                parts.Add($"{request.DenyToAllowCount} will newly be allowed");
            }

            summary.Append(string.Join(", ", parts)).Append('.');

            IEnumerable<string> subjects = request.Flips
                .Select(flip => flip.SubjectEmail)
                .Where(email => !string.IsNullOrWhiteSpace(email))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .Take(5)!;
            string subjectList = string.Join(", ", subjects);
            if (!string.IsNullOrEmpty(subjectList))
            {
                summary.Append(" Affected subjects include ").Append(subjectList).Append('.');
            }
        }

        if (!request.SampledFromHistory)
        {
            summary.Append(" No recorded decisions were available, so this used current assignments with empty context; treat it as a lower bound.");
        }

        return Task.FromResult(new ImpactNarrationResult(summary.ToString()));
    }

    public Task<ConfigAdvisorResult> SummarizeFindingsAsync(ConfigAdvisorRequest request, CancellationToken cancellationToken)
    {
        if (request.Findings.Count == 0)
        {
            return Task.FromResult(new ConfigAdvisorResult(
                "No governance issues were found. The configuration looks healthy.",
                []));
        }

        int high = request.Findings.Count(finding => string.Equals(finding.Severity, "HIGH", StringComparison.OrdinalIgnoreCase));
        int medium = request.Findings.Count(finding => string.Equals(finding.Severity, "MEDIUM", StringComparison.OrdinalIgnoreCase));
        int low = request.Findings.Count(finding => string.Equals(finding.Severity, "LOW", StringComparison.OrdinalIgnoreCase));

        List<ConfigFindingSuggestion> suggestions = request.Findings
            .Select(finding => new ConfigFindingSuggestion(finding.Id, SuggestFix(finding)))
            .ToList();

        return Task.FromResult(new ConfigAdvisorResult(ComposeAdvisorSummary(request, high, medium, low), suggestions));
    }

    // Deterministic, structured advisor narrative used offline/in CI and whenever no model is
    // configured. It mirrors the section layout the real model is prompted to produce (Executive
    // Summary → Key Observations → Potential Impact → Recommended Actions → Overall Assessment) so the
    // UI renders a consistent, scannable review rather than a bare count. Grounded entirely in the
    // deterministic findings; it never invents issues.
    private static string ComposeAdvisorSummary(ConfigAdvisorRequest request, int high, int medium, int low)
    {
        int total = request.Findings.Count;
        var byKind = request.Findings
            .GroupBy(finding => finding.Kind, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(group => group.Key, group => group.ToList(), StringComparer.OrdinalIgnoreCase);

        int Count(string kind) => byKind.TryGetValue(kind, out List<ConfigFindingFact>? list) ? list.Count : 0;
        string Keys(string kind) => byKind.TryGetValue(kind, out List<ConfigFindingFact>? list)
            ? JoinKeys(list.Select(finding => finding.EntityKey))
            : string.Empty;

        int deadContext = Count("DEAD_CONTEXT_ATTRIBUTE");
        int unguarded = Count("PRIVILEGED_UNGUARDED");
        int orphan = Count("ORPHAN_PERMISSION");
        int unused = Count("UNUSED_ROLE");
        int duplicate = Count("DUPLICATE_ROLES");
        int unfireable = Count("UNFIREABLE_RULE");
        int stale = Count("STALE_DRAFT");
        bool deadContextDominant = deadContext > 0 && deadContext >= (total + 1) / 2;

        var b = new StringBuilder();
        b.AppendLine("## Executive Summary");
        b.Append("This review surfaced **").Append(total).Append(total == 1 ? " finding**" : " findings**")
            .Append(" (").Append(high).Append(" high, ").Append(medium).Append(" medium, ").Append(low).Append(" low). ");
        if (deadContextDominant)
        {
            b.Append("The findings consistently point to policies that depend on context attributes never observed in recorded decisions — an integration gap between policy definitions and the runtime requests consuming applications send, rather than isolated policy defects.");
        }
        else if (high > 0)
        {
            b.Append("The high-severity items represent privileged access that is not yet constrained by any policy and should be addressed first.");
        }
        else
        {
            b.Append("Individually these are low-to-medium risk, but collectively they reflect configuration hygiene that will affect maintainability and future scale if left unaddressed.");
        }

        b.AppendLine().AppendLine();
        b.AppendLine("## Key Observations");
        if (deadContext > 0)
        {
            b.Append("- **").Append(deadContext).Append(deadContext == 1 ? " dead context attribute:** policy " : " dead context attributes:** policies ")
                .Append(Keys("DEAD_CONTEXT_ATTRIBUTE")).AppendLine(" reference context attributes never seen in decisions, so those conditions may never evaluate as intended.");
        }

        if (unguarded > 0)
        {
            b.Append("- **").Append(unguarded).Append(unguarded == 1 ? " privileged role without a guarding policy:** " : " privileged roles without a guarding policy:** ")
                .Append(Keys("PRIVILEGED_UNGUARDED")).AppendLine(" grant privileged permissions with nothing constraining when they apply.");
        }

        if (orphan > 0)
        {
            b.Append("- **").Append(orphan).AppendLine(orphan == 1 ? " orphaned permission:** granted by no published role, so it can never be exercised." : " orphaned permissions:** granted by no published role, so they can never be exercised.");
        }

        if (unused > 0)
        {
            b.Append("- **").Append(unused).AppendLine(unused == 1 ? " unused role:** assigned to no active subject — dormant surface area." : " unused roles:** assigned to no active subject — dormant surface area.");
        }

        if (duplicate > 0)
        {
            b.Append("- **").Append(duplicate).AppendLine(" near-duplicate role pair(s):** heavily overlapping permission sets that are candidates for consolidation.");
        }

        if (unfireable > 0)
        {
            b.Append("- **").Append(unfireable).AppendLine(" unfireable rule(s):** contradictory conditions that can never match.");
        }

        if (stale > 0)
        {
            b.Append("- **").Append(stale).AppendLine(" stale draft(s):** left unpublished past the review window.");
        }

        b.AppendLine();
        b.AppendLine("## Potential Impact");
        if (deadContext > 0)
        {
            b.AppendLine("- Fine-grained, attribute-based conditions may silently never fire, reducing the real effectiveness of your authorization controls and giving false confidence in enforcement.");
        }

        if (unguarded > 0)
        {
            b.AppendLine("- Unconstrained privileged access widens the blast radius of a compromised or over-provisioned account.");
        }

        b.AppendLine("- Orphaned, duplicate, and dormant objects erode maintainability and make each future review and scaling step harder.");

        b.AppendLine();
        b.AppendLine("## Recommended Actions");
        int priority = 1;
        if (deadContext > 0)
        {
            b.Append("- **Priority ").Append(priority++).AppendLine(" —** Validate the context payloads consuming applications actually send at decision time before editing policy logic; confirm each referenced attribute is emitted.");
        }

        if (unguarded > 0)
        {
            b.Append("- **Priority ").Append(priority++).Append(" —** Attach guarding policies to the privileged role(s) (").Append(Keys("PRIVILEGED_UNGUARDED")).AppendLine(") so their access is conditional.");
        }

        if (orphan > 0 || unused > 0 || duplicate > 0 || stale > 0)
        {
            b.Append("- **Priority ").Append(priority++).AppendLine(" —** Retire orphaned permissions, archive unused roles, consolidate duplicates, and clear stale drafts to shrink the surface area.");
        }

        b.AppendLine("- **Prevent recurrence —** Add validation and monitoring for required context attributes, cover policies with tests, and run this advisor as a lint gate in CI so regressions surface before release.");

        b.AppendLine();
        b.AppendLine("## Overall Assessment");
        string rating = high > 0 ? "At risk" : medium > 0 ? "Needs attention" : "Healthy";
        b.Append("**").Append(rating).Append("** — ");
        if (high > 0)
        {
            b.Append("high-severity gaps are present; work the actions above in order, starting with the root-cause fixes.");
        }
        else if (medium > 0)
        {
            b.Append("no high-severity gaps, but several medium items warrant attention to keep enforcement effective and the model tidy.");
        }
        else
        {
            b.Append("only low-severity hygiene items remain; address them opportunistically and keep the lint gate in place.");
        }

        return b.ToString().TrimEnd();
    }

    // Renders up to five distinct entity keys as inline code, appending an ellipsis when more exist,
    // so observations name the actual roles/policies involved without becoming unbounded.
    private static string JoinKeys(IEnumerable<string?> keys)
    {
        List<string> distinct = keys
            .Where(key => !string.IsNullOrWhiteSpace(key))
            .Select(key => key!)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();
        if (distinct.Count == 0)
        {
            return "(unnamed)";
        }

        const int max = 5;
        string shown = string.Join(", ", distinct.Take(max).Select(key => $"`{key}`"));
        return distinct.Count > max ? $"{shown}, …" : shown;
    }

    // Deterministic, per-kind remediation hint so offline/CI output remains useful and testable.
    private static string SuggestFix(ConfigFindingFact finding) => finding.Kind switch
    {
        "ORPHAN_PERMISSION" => "Grant this permission to a role, or remove it if it is no longer needed.",
        "UNUSED_ROLE" => "Assign this role to a subject, or archive it to reduce surface area.",
        "PRIVILEGED_UNGUARDED" => "Attach a policy that constrains when this privileged access applies.",
        "DEAD_CONTEXT_ATTRIBUTE" => "Confirm callers supply this context attribute, or simplify the policy that references it.",
        "STALE_DRAFT" => "Publish this draft if it is ready, or delete it to avoid confusion.",
        "UNFIREABLE_RULE" => "Correct the contradictory conditions so the rule can match.",
        "DUPLICATE_ROLES" => "Consolidate these near-duplicate roles into one to simplify administration.",
        _ => "Review this finding and take the appropriate corrective action.",
    };

    public Task<SodRuleDraftResult> DraftSodRuleAsync(SodRuleDraftRequest request, CancellationToken cancellationToken)
    {
        string instruction = (request.Instruction ?? string.Empty).ToLowerInvariant();
        var warnings = new List<string> { StubWarning };

        // Prefer two distinct permission keys mentioned in the instruction; otherwise two distinct
        // actions; grounded only in the real vocabulary so the draft never invents a permission.
        List<string> permissionKeys = MentionedDistinct(instruction, request.KnownPermissionKeys);
        List<string> actions = MentionedDistinct(instruction, request.KnownActions);

        SodMatcherDraft? matcherA = null;
        SodMatcherDraft? matcherB = null;

        if (permissionKeys.Count >= 2)
        {
            matcherA = new SodMatcherDraft(permissionKeys[0], null, null);
            matcherB = new SodMatcherDraft(permissionKeys[1], null, null);
        }
        else if (actions.Count >= 2)
        {
            matcherA = new SodMatcherDraft(null, null, actions[0]);
            matcherB = new SodMatcherDraft(null, null, actions[1]);
        }

        if (matcherA is null || matcherB is null)
        {
            warnings.Add("Could not ground two distinct permissions from the instruction; edit the matchers before saving.");
            matcherA ??= new SodMatcherDraft(null, null, null);
            matcherB ??= new SodMatcherDraft(null, null, null);
        }

        string sideA = DescribeMatcher(matcherA);
        string sideB = DescribeMatcher(matcherB);
        string name = $"Separate {sideA} and {sideB}";
        string rationale = $"No single role or user should be able to both {sideA} and {sideB}.";

        return Task.FromResult(new SodRuleDraftResult(name, rationale, "HIGH", matcherA, matcherB, warnings));
    }

    private static List<string> MentionedDistinct(string instruction, IReadOnlyList<string> vocabulary) =>
        vocabulary
            .Where(term => !string.IsNullOrWhiteSpace(term)
                && instruction.Contains(term.ToLowerInvariant(), StringComparison.OrdinalIgnoreCase))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(term => instruction.IndexOf(term.ToLowerInvariant(), StringComparison.OrdinalIgnoreCase))
            .ToList();

    private static string DescribeMatcher(SodMatcherDraft matcher) =>
        matcher.PermissionKey
        ?? (matcher.Resource is not null && matcher.Action is not null
            ? $"{matcher.Action} {matcher.Resource}"
            : matcher.Action ?? matcher.Resource ?? "(unspecified)");

    public Task<AccessReviewSummaryResult> SummarizeAccessReviewAsync(AccessReviewSummaryRequest request, CancellationToken cancellationToken)
    {
        if (request.Items.Count == 0)
        {
            return Task.FromResult(new AccessReviewSummaryResult(
                $"{request.SubjectLabel} holds no active access to review.",
                []));
        }

        var summary = new StringBuilder();
        summary.Append(request.SubjectLabel).Append(" holds ").Append(request.ItemCount)
            .Append(request.ItemCount == 1 ? " active grant" : " active grants")
            .Append(" (").Append(request.KeepCount).Append(" to keep, ")
            .Append(request.RevokeCount).Append(" to revoke, ")
            .Append(request.ReviewCount).Append(" needing attention). ");
        summary.Append(request.RevokeCount + request.ReviewCount > 0
            ? "Start with the flagged grants below before certifying the rest."
            : "Nothing looks anomalous; a routine certification should suffice.");

        // Echo the deterministic recommendation reason back as the per-item rationale so offline/CI
        // output is useful and testable. The model never changes the recommendation itself.
        List<AccessReviewItemRationale> rationales = request.Items
            .Select(item => new AccessReviewItemRationale(item.Id, RationaleFor(item)))
            .ToList();

        return Task.FromResult(new AccessReviewSummaryResult(summary.ToString(), rationales));
    }

    private static string RationaleFor(AccessReviewItemFact item)
    {
        var parts = new List<string> { item.RecommendationReason };
        if (item.Privileged)
        {
            parts.Add("privileged role");
        }

        if (item.Dormant)
        {
            parts.Add(item.LastUsedDaysAgo is int days ? $"last used {days}d ago" : "never exercised");
        }

        if (item.PeerCount == 0)
        {
            parts.Add("no peers hold this role");
        }

        return string.Join("; ", parts) + ".";
    }

    public Task<AuditNarrationResult> NarrateAuditAsync(AuditNarrationRequest request, CancellationToken cancellationToken)
    {
        if (request.Events.Count == 0)
        {
            return Task.FromResult(new AuditNarrationResult(
                "No audit activity was recorded in the selected window.",
                []));
        }

        var summary = new StringBuilder();
        summary.Append(request.TotalEvents)
            .Append(request.TotalEvents == 1 ? " audit event" : " audit events")
            .Append(" across ").Append(request.ByApplication.Count)
            .Append(request.ByApplication.Count == 1 ? " application" : " applications")
            .Append(" between ").Append(request.FromUtc.ToString("yyyy-MM-dd"))
            .Append(" and ").Append(request.ToUtc.ToString("yyyy-MM-dd")).Append(". ");

        AuditGroupFact? topActor = request.ByActor.FirstOrDefault();
        if (topActor is not null)
        {
            summary.Append("Most active actor: ").Append(topActor.Key)
                .Append(" (").Append(topActor.Count)
                .Append(topActor.Count == 1 ? " change). " : " changes). ");
        }

        summary.Append(request.TopDenyReasons.Count > 0
            ? $"{request.TopDenyReasons.Sum(reason => reason.Count)} access denials were also recorded."
            : "No access denials were recorded in this window.");

        // One section per change type, each citing the concrete event ids it covers, so offline/CI
        // output is deterministic and every claim is grounded in real events.
        List<AuditNarrativeSection> sections = request.Events
            .GroupBy(e => e.EventType, StringComparer.OrdinalIgnoreCase)
            .OrderByDescending(g => g.Count())
            .ThenBy(g => g.Key, StringComparer.OrdinalIgnoreCase)
            .Select(group =>
            {
                List<string> eventIds = group.Select(e => e.EventId).ToList();
                string actors = string.Join(", ", group
                    .Where(e => !string.IsNullOrWhiteSpace(e.ActorLabel))
                    .Select(e => e.ActorLabel!)
                    .Distinct(StringComparer.OrdinalIgnoreCase));
                string detail = $"{eventIds.Count} {group.Key} event{(eventIds.Count == 1 ? string.Empty : "s")}"
                    + (actors.Length > 0 ? $" by {actors}." : ".");
                return new AuditNarrativeSection(group.Key, detail, eventIds);
            })
            .ToList();

        return Task.FromResult(new AuditNarrationResult(summary.ToString(), sections));
    }

    public Task<AccessSearchPlanResult> PlanAccessSearchAsync(AccessSearchPlanRequest request, CancellationToken cancellationToken)
    {
        // Deterministic NL→spec planner: pick an entity from question keywords, then ground each
        // filter value strictly against the supplied vocabulary. Because values are only ever taken
        // from the real vocabulary and the schema field list, the fake can never invent a field or
        // emit anything but a closed, safe spec.
        string question = (request.Question ?? string.Empty).ToLowerInvariant();

        string entity = ChooseEntity(question, request.Schema);
        AccessSearchEntitySchema? entitySchema = request.Schema
            .FirstOrDefault(s => string.Equals(s.Entity, entity, StringComparison.OrdinalIgnoreCase));
        if (entitySchema is null)
        {
            return Task.FromResult(new AccessSearchPlanResult(string.Empty, [], "No searchable entity matched the question."));
        }

        var allowed = new HashSet<string>(entitySchema.Fields, StringComparer.OrdinalIgnoreCase);
        var filters = new List<AccessSearchPlanFilter>();
        AccessSearchVocabulary vocab = request.Vocabulary;

        // Prefer the most specific grounding: an explicit permission key, then action, then resource.
        string? permissionKey = FirstMentioned(question, vocab.PermissionKeys);
        if (permissionKey is not null && allowed.Contains("permission"))
        {
            filters.Add(new AccessSearchPlanFilter("permission", "eq", permissionKey));
        }
        else
        {
            string? action = FirstMentioned(question, vocab.Actions);
            if (action is not null && allowed.Contains("action"))
            {
                filters.Add(new AccessSearchPlanFilter("action", "eq", action));
            }

            string? resource = FirstMentioned(question, vocab.Resources);
            if (resource is not null && allowed.Contains("resource"))
            {
                filters.Add(new AccessSearchPlanFilter("resource", "eq", resource));
            }
        }

        string? roleKey = FirstMentioned(question, vocab.RoleKeys);
        if (roleKey is not null && allowed.Contains("role")
            && !string.Equals(entity, "role", StringComparison.OrdinalIgnoreCase))
        {
            filters.Add(new AccessSearchPlanFilter("role", "eq", roleKey));
        }

        string? resourceId = FirstMentioned(question, vocab.ResourceIds);
        if (resourceId is not null && allowed.Contains("resourceId"))
        {
            filters.Add(new AccessSearchPlanFilter("resourceId", "contains", resourceId));
        }

        // Lifecycle status: "inactive"/"disabled" roles or permissions → status is not ACTIVE.
        if (allowed.Contains("status") && (question.Contains("inactive") || question.Contains("disabled")
            || question.Contains("deactivated") || question.Contains("not active") || question.Contains("archived")
            || question.Contains("deprecated")))
        {
            if (question.Contains("archived"))
            {
                filters.Add(new AccessSearchPlanFilter("status", "eq", "ARCHIVED"));
            }
            else if (question.Contains("deprecated"))
            {
                filters.Add(new AccessSearchPlanFilter("status", "eq", "DEPRECATED"));
            }
            else if (question.Contains("disabled"))
            {
                filters.Add(new AccessSearchPlanFilter("status", "eq", "DISABLED"));
            }
            else
            {
                filters.Add(new AccessSearchPlanFilter("status", "neq", "ACTIVE"));
            }
        }

        // Assignment lifecycle: "expired"/"past expiry" or "revoked" map to the assignment state.
        if (allowed.Contains("state"))
        {
            if (question.Contains("expir") || question.Contains("lapsed") || question.Contains("past due"))
            {
                filters.Add(new AccessSearchPlanFilter("state", "eq", "EXPIRED"));
            }
            else if (question.Contains("revoked"))
            {
                filters.Add(new AccessSearchPlanFilter("state", "eq", "REVOKED"));
            }
        }

        string? aggregate = question.Contains("how many") || question.Contains("count")
            || question.Contains("number of")
            ? "count"
            : null;

        // A per-group count ("how many permissions does each role grant") maps to a groupBy over one
        // of the entity's relationships; groupBy takes precedence over a scalar count.
        string? groupBy = null;
        bool perGroup = question.Contains("per ") || question.Contains("each ") || question.Contains(" by ");
        if (perGroup)
        {
            if (string.Equals(entity, "role", StringComparison.OrdinalIgnoreCase) && question.Contains("permission"))
            {
                groupBy = "permissions";
            }
            else if (string.Equals(entity, "role", StringComparison.OrdinalIgnoreCase) && question.Contains("assignment"))
            {
                groupBy = "assignments";
            }
            else if (string.Equals(entity, "permission", StringComparison.OrdinalIgnoreCase) && question.Contains("role"))
            {
                groupBy = "roles";
            }
        }

        // A relationship include ("show the pricing-admin role and its permissions") attaches the
        // named related records to each result; include takes precedence over groupBy and count.
        string? include = null;
        bool includeCue = question.Contains("and its") || question.Contains("and their")
            || question.Contains("with its") || question.Contains("with their")
            || question.Contains("include") || question.Contains("along with") || question.Contains("expand");
        if (includeCue)
        {
            include = (entitySchema.Relationships ?? [])
                .FirstOrDefault(r => question.Contains(r.ToLowerInvariant())
                    || question.Contains(r.ToLowerInvariant().TrimEnd('s')));
        }

        string explanation = (include is not null ? $"Showing {entity} with {include}"
                : groupBy is not null ? $"Counted {entity} by {groupBy}"
                : aggregate == "count" ? $"Counted {entity} records"
                : $"Interpreted as a {entity} search")
            + (filters.Count > 0
                ? " filtered by " + string.Join(", ", filters.Select(f => $"{f.Field} {f.Operator} '{f.Value}'")) + "."
                : " with no additional filters.");

        return Task.FromResult(new AccessSearchPlanResult(entity, filters, explanation, aggregate, groupBy, include));
    }

    private static string ChooseEntity(string question, IReadOnlyList<AccessSearchEntitySchema> schema)
    {
        bool Has(string entity) => schema.Any(s => string.Equals(s.Entity, entity, StringComparison.OrdinalIgnoreCase));

        // Expiry/revocation questions are about assignments even when phrased about "users", because
        // only the assignment entity carries lifecycle state and an expiry date.
        if (Has("assignment") && (question.Contains("expir") || question.Contains("lapsed")
            || question.Contains("past due") || question.Contains("revoked")))
        {
            return "assignment";
        }

        if (Has("subject") && (question.Contains("who") || question.Contains("everyone")
            || question.Contains("people") || question.Contains("users") || question.Contains("subject")))
        {
            return "subject";
        }

        // Generic registry entities. Checked before the broad role/permission/assignment matches so a
        // more specific entity ("assignment attribute", "reference data") is not shadowed.
        if (Has("assignmentAttribute") && question.Contains("attribute"))
        {
            return "assignmentAttribute";
        }

        if (Has("sodRule") && (question.Contains("separation of duties") || question.Contains("sod")
            || question.Contains("toxic") || question.Contains("segregation") || question.Contains("conflict")))
        {
            return "sodRule";
        }

        if (Has("referenceData") && question.Contains("reference"))
        {
            return "referenceData";
        }

        if (Has("oidcProvider") && (question.Contains("oidc") || question.Contains("issuer")
            || question.Contains("identity provider") || question.Contains("provider")))
        {
            return "oidcProvider";
        }

        if (Has("auditEvent") && (question.Contains("audit") || question.Contains("event")))
        {
            return "auditEvent";
        }

        if (Has("decision") && question.Contains("decision"))
        {
            return "decision";
        }

        if (Has("aiPromptLog") && question.Contains("prompt"))
        {
            return "aiPromptLog";
        }

        if (Has("aiInvocation") && question.Contains("invocation"))
        {
            return "aiInvocation";
        }

        if (Has("application") && question.Contains("application"))
        {
            return "application";
        }

        if (Has("role") && question.Contains("role"))
        {
            return "role";
        }

        if (Has("policy") && (question.Contains("policy") || question.Contains("policies")))
        {
            return "policy";
        }

        if (Has("assignment") && question.Contains("assignment"))
        {
            return "assignment";
        }

        if (Has("permission") && question.Contains("permission"))
        {
            return "permission";
        }

        // Default to the role entity, the most common "which X can do Y" question.
        return Has("role") ? "role" : schema.Count > 0 ? schema[0].Entity : string.Empty;
    }

    private static string? FirstMentioned(string question, IReadOnlyList<string> vocabulary) =>
        vocabulary
            .Where(term => !string.IsNullOrWhiteSpace(term)
                && question.Contains(term.ToLowerInvariant(), StringComparison.OrdinalIgnoreCase))
            .OrderByDescending(term => term.Length)
            .FirstOrDefault();

    // Adds a deterministic, grounded sentence describing the most likely root cause based on the
    // gathered diagnostics. Mirrors the analysis the live model produces, so offline/CI output is
    // still useful and testable.
    private static void AppendDiagnosticNarrative(StringBuilder narrative, DecisionDiagnostics? diagnostics)
    {
        if (diagnostics is null)
        {
            return;
        }

        if (!diagnostics.PermissionExists)
        {
            narrative.Append(diagnostics.ResourceTypeKnown
                ? " The resource type is known, but no permission defines this action for it"
                : " No permission is defined for this resource type");
            if (diagnostics.ResourceTypeKnown && diagnostics.AvailableActionsForResourceType.Count > 0)
            {
                narrative.Append(" (available actions: ")
                    .Append(string.Join(", ", diagnostics.AvailableActionsForResourceType))
                    .Append(')');
            }

            narrative.Append('.');
            return;
        }

        if (!diagnostics.SubjectKnown)
        {
            narrative.Append(" The subject has no assignment in this application");
            if (diagnostics.SimilarKnownSubjectEmails.Count > 0)
            {
                narrative.Append(", but a similar known address exists (")
                    .Append(string.Join(", ", diagnostics.SimilarKnownSubjectEmails))
                    .Append("), which strongly suggests a misspelled email");
            }

            narrative.Append('.');
            return;
        }

        if (diagnostics.SubjectRoleKeys.Count > 0 && diagnostics.RolesGrantingPermission.Count > 0)
        {
            narrative.Append(" The subject holds ")
                .Append(string.Join(", ", diagnostics.SubjectRoleKeys))
                .Append(", but this action is only granted by ")
                .Append(string.Join(", ", diagnostics.RolesGrantingPermission))
                .Append('.');
            return;
        }

        List<PolicyDiagnostic> denies = diagnostics.RelevantPolicies
            .Where(policy => policy.Matched && string.Equals(policy.Effect, "DENY", StringComparison.OrdinalIgnoreCase))
            .ToList();
        if (denies.Count > 0)
        {
            narrative.Append(" A DENY policy matched: ")
                .Append(string.Join(", ", denies.Select(policy => policy.PolicyKey)))
                .Append('.');
        }
    }

    private static IReadOnlyList<string> BuildRemediation(DecisionExplanationRequest request)
    {
        DecisionDiagnostics? diagnostics = request.Diagnostics;
        var steps = new List<string>();

        if (diagnostics is null)
        {
            steps.Add("Review the subject's role assignments and any policy conditions that could block this action, then re-run the simulation.");
            return steps;
        }

        if (!diagnostics.PermissionExists)
        {
            if (!diagnostics.ResourceTypeKnown)
            {
                steps.Add($"Confirm the resource type '{request.ResourceType}' is spelled correctly.");
                if (diagnostics.KnownResourceTypes.Count > 0)
                {
                    steps.Add("Known resource types: " + string.Join(", ", diagnostics.KnownResourceTypes) + ".");
                }
            }
            else
            {
                steps.Add($"Confirm the action '{request.Action}' is correct for resource type '{request.ResourceType}'.");
                if (diagnostics.AvailableActionsForResourceType.Count > 0)
                {
                    steps.Add("Available actions: " + string.Join(", ", diagnostics.AvailableActionsForResourceType) + ".");
                }
                steps.Add("If this action should exist, define a permission for it.");
            }

            return steps;
        }

        if (!diagnostics.SubjectKnown)
        {
            if (diagnostics.SimilarKnownSubjectEmails.Count > 0)
            {
                steps.Add("Re-run the check using one of these existing addresses: " + string.Join(", ", diagnostics.SimilarKnownSubjectEmails) + ".");
            }

            steps.Add("If the subject is correct, create an assignment granting them a role that includes this permission.");
            return steps;
        }

        if (diagnostics.ActiveAssignmentCount == 0
            && (diagnostics.RevokedAssignmentCount > 0 || diagnostics.ExpiredAssignmentCount > 0 || diagnostics.PendingAssignmentCount > 0))
        {
            steps.Add($"The subject has no active assignment (revoked: {diagnostics.RevokedAssignmentCount}, expired: {diagnostics.ExpiredAssignmentCount}, not-yet-valid: {diagnostics.PendingAssignmentCount}).");
            steps.Add("Reinstate or renew an assignment so it is active now.");
            return steps;
        }

        if (diagnostics.RolesGrantingPermission.Count > 0)
        {
            steps.Add("Assign one of these roles that grant the permission: " + string.Join(", ", diagnostics.RolesGrantingPermission) + ".");
            steps.Add("Alternatively, add this permission to a role the subject already holds.");
            return steps;
        }

        List<PolicyDiagnostic> denies = diagnostics.RelevantPolicies
            .Where(policy => policy.Matched && string.Equals(policy.Effect, "DENY", StringComparison.OrdinalIgnoreCase))
            .ToList();
        if (denies.Count > 0)
        {
            steps.Add("Review the blocking DENY policy: " + string.Join(", ", denies.Select(policy => policy.PolicyKey)) + ".");
            steps.Add("Adjust the policy conditions or the request context so the deny no longer applies.");
            return steps;
        }

        if (diagnostics.ReferencedContextAttributes.Count > 0)
        {
            IEnumerable<string> missing = diagnostics.ReferencedContextAttributes
                .Where(attribute => !diagnostics.ProvidedContextKeys.Contains(attribute, StringComparer.OrdinalIgnoreCase));
            string missingList = string.Join(", ", missing);
            if (!string.IsNullOrEmpty(missingList))
            {
                steps.Add("Supply the required context attribute(s): " + missingList + ".");
            }
        }

        if (steps.Count == 0)
        {
            steps.Add("Review the applicable policies and the request context, then re-run the simulation.");
        }

        return steps;
    }

    private static string Truncate(string value, int maxLength) =>
        value.Length <= maxLength ? value : value[..maxLength];
}
